### ISSUE TITLE
Remove Account and Password Reset functionality

### ISSUE THREAD

**Issue by holsee** [manusajith/elixirjobs#10]
There currently is no way to reset passwords or to delete the account.

**Comment by manusajith** [comment]
@holsee Would you be interested in sending a PR?

I also labelled the issue with `Hacktoberfest`, hope we get some love ❤️

**Comment by holsee** [comment]
I run the Belfast Elixir meetup, maybe we could mob program it sometime this / next month :)

**Comment by vraravam** [comment]
I would like to take a stab at this - but, im unable to move beyond `mix deps.get` - since the dependencies bomb out.
```
Failed to use "poison" (version 1.4.0) because
  deps/exrethinkdb/mix.exs requires 1.4.0
  phoenix (version 1.3.0) requires ~> 2.2 or ~> 3.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

**Comment by manusajith** [comment]
@vraravam `exrethinkdb` is one of the major blockers in keeping the deps upto date. To upgrade `exrethinkdb` we need to make changes in the current codebase related to connection, query etc.

**Comment by vraravam** [comment]
@manusajith - that's fine, I was just trying to clone and get the app "up and running" on my local - even that is failing due to `mix deps.get` failing.
